baseURL: https://consequently.org/
languageCode: en-gb
title: consequently.org
summaryLength: 200

copyright: Greg Restall

markup:
  goldmark:
    renderer:
      unsafe: true


params:
  slogan: "Greg Restall’s home on the internet."
